### ISSUE TITLE
Installation instructors and documentations

### ISSUE THREAD

**Issue by StevenLiuWen** [FishWoWater/ARCSim-For-SMPL#2]
Hi, @FishWoWater, 

Thanks for this cool project. I have encountered some problems in installation. After running the `python exec.py`, I have received the following errors;

```Bash

[ 97%] Building CXX object v0.2.1/CMakeFiles/arcsim_0.2.1.dir/hylc/strain/strain_valgradhess.cpp.o
[ 98%] Building CXX object v0.2.1/CMakeFiles/arcsim_0.2.1.dir/hylc/strain/strain_value.cpp.o
[100%] Linking CXX executable ../bin/arcsim_0.2.1
Undefined symbols for architecture x86_64:
  "___kmpc_end_reduce_nowait", referenced from:
      _.omp_outlined..2 in strainlimiting.cpp.o
      _.omp_outlined..3 in trustregion.cpp.o
      _.omp_outlined..4 in trustregion.cpp.o
      _.omp_outlined..1 in hylc.cpp.o
      _.omp_outlined..3 in hylc.cpp.o
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in auglag.cpp.o
      _.omp_outlined..2 in auglag.cpp.o
      _.omp_outlined..3 in auglag.cpp.o
      _.omp_outlined. in collisionutil.cpp.o
      _.omp_outlined..1 in collisionutil.cpp.o
      _.omp_outlined. in nearobs.cpp.o
      _.omp_outlined. in plasticity.cpp.o
      ...

  "_omp_set_num_threads", referenced from:
      for_overlapping_faces(std::__1::vector<AccelStruct*, std::__1::allocator<AccelStruct*> > const&, std::__1::vector<AccelStruct*, std::__1::allocator<AccelStruct*> > const&, double, void (*)(Face const*, Face const*), bool) in collisionutil.cpp.o
      for_faces_overlapping_obstacles(std::__1::vector<AccelStruct*, std::__1::allocator<AccelStruct*> > const&, std::__1::vector<AccelStruct*, std::__1::allocator<AccelStruct*> > const&, double, void (*)(Face const*, Face const*), bool) in collisionutil.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/arcsim_0.2.1] Error 1
make[1]: *** [v0.2.1/CMakeFiles/arcsim_0.2.1.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "exec.py", line 67, in <module>
    build(sourcedir=sourcedir, builddir=builddir, debug=args['debug'])
  File "exec.py", line 20, in build
    subprocess.check_call(['cmake', '--build', '.'] +
  File "/Users/stevenxxliu/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j']' returned non-zero exit status 2.

```

I wonder if there is any installation documentation? Thanks in advance.

My platform is:

Operation system:
* macOS BigSur, Intel Core i7
* Apple clang version 12.0.5 (clang-1205.0.22.11)

dependencies:
* cmake: 3.23.2
* openmp: 14.0.6
* opencv: 4.5.5_2
* boost: 1.78.0_1

**Comment by FishWoWater** [comment]
Hi, @StevenLiuWen 

For installation it should work with `python exec.py` or `mkdir build-Release && cd build-Release && cmake .. &&make -j8`. Documentation of original arcsim-hylc project can be found [here](https://github.com/FishWoWater/ARCSim-For-SMPL/blob/master/README_HYLC.md), but there exist no more instructions.

I am afraid I don't have any good suggestions for your situation. It seems that openmp library can not be found during linkage.  Ensure that cmake found openmp and its library successfully. A non-elegant way to solve this problem is to comment out all #omp wrapper, but it would be very slow.

Anyway,  it works on ubuntu16.04 / 18.04 with cmake 3.20 and boost 1.68, openmp 201511

Best

**Comment by StevenLiuWen** [comment]
Hi, @FishWoWater 

Thanks for your quick reply. It seems that I have complied successfully in MacOS with both Intel and M1, which needs some modification of the CMAKELists.txt (just switching to the LLVM Clang compilers).
