### ISSUE TITLE
Missing the files "meshes/vto_tshirt.obj" to run the example 

### ISSUE THREAD

**Issue by StevenLiuWen** [FishWoWater/ARCSim-For-SMPL#3]
Hi, @FishWoWater 

Thanks for your previous reply to help me resolve the problem of installation. After running the example, I have met following errors:

```Bash
./build-Release/bin/arcsim_0.2.1 simulate smpl_demo/jump.json
Error: failed to open file meshes/vto_tshirt.obj
1 241
smpl motion parsed
```

It seems that there is a missing `vto_tshirt.obj` file in `meshes/`. 

Thanks in advance.

**Comment by FishWoWater** [comment]
@StevenLiuWen Sorry for my carelessness, already updated.

**Comment by StevenLiuWen** [comment]
@FishWoWater, Thanks for your quick reply and update. Everything is running fine now.
